// FETCH_GUEST_SESSION_ID ACTION NAMES

export const FETCH_GUEST_SESSION_ID = 'FETCH_GUEST_SESSION_ID';
export const FETCH_GUEST_SESSION_ID_PENDING = 'FETCH_GUEST_SESSION_ID_PENDING';
export const FETCH_GUEST_SESSION_ID_FULFILLED = 'FETCH_GUEST_SESSION_ID_FULFILLED';
export const FETCH_GUEST_SESSION_ID_REJECTED = 'FETCH_GUEST_SESSION_ID_REJECTED';

// FETCH_SESSION_ID ACTION NAMES

export const FETCH_SESSION_ID = 'FETCH_SESSION_ID';
export const FETCH_SESSION_ID_PENDING = 'FETCH_SESSION_ID_PENDING';
export const FETCH_SESSION_ID_FULFILLED = 'FETCH_SESSION_ID_FULFILLED';
export const FETCH_SESSION_ID_REJECTED = 'FETCH_SESSION_ID_REJECTED';

// FETCH_REQUEST_TOKEN ACTION NAMES

export const FETCH_REQUEST_TOKEN = 'FETCH_REQUEST_TOKEN';
export const FETCH_REQUEST_TOKEN_PENDING = 'FETCH_REQUEST_TOKEN_PENDING';
export const FETCH_REQUEST_TOKEN_FULFILLED = 'FETCH_REQUEST_TOKEN_FULFILLED';
export const FETCH_REQUEST_TOKEN_REJECTED = 'FETCH_REQUEST_TOKEN_REJECTED';

// FETCH_USER_INFO ACTION NAMES

export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_INFO_PENDING = 'FETCH_USER_INFO_PENDING';
export const FETCH_USER_INFO_FULFILLED = 'FETCH_USER_INFO_FULFILLED';
export const FETCH_USER_INFO_REJECTED = 'FETCH_USER_INFO_REJECTED';

// FETCH_API_CONFIGURATION ACTION NAMES

export const FETCH_API_CONFIGURATION = 'FETCH_API_CONFIGURATION';
export const FETCH_API_CONFIGURATION_PENDING = 'FETCH_API_CONFIGURATION_PENDING';
export const FETCH_API_CONFIGURATION_FULFILLED = 'FETCH_API_CONFIGURATION_FULFILLED';
export const FETCH_API_CONFIGURATION_REJECTED = 'FETCH_API_CONFIGURATION_REJECTED';

// FETCH_POPULAR_MOVIES ACTION NAMES

export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_POPULAR_MOVIES_PENDING = 'FETCH_POPULAR_MOVIES_PENDING';
export const FETCH_POPULAR_MOVIES_FULFILLED = 'FETCH_POPULAR_MOVIES_FULFILLED';
export const FETCH_POPULAR_MOVIES_REJECTED = 'FETCH_POPULAR_MOVIES_REJECTED';

// FETCH_POPULAR_TVSHOWS ACTION NAMES

export const FETCH_POPULAR_TVSHOWS = 'FETCH_POPULAR_TVSHOWS';
export const FETCH_POPULAR_TVSHOWS_PENDING = 'FETCH_POPULAR_TVSHOWS_PENDING';
export const FETCH_POPULAR_TVSHOWS_FULFILLED = 'FETCH_POPULAR_TVSHOWS_FULFILLED';
export const FETCH_POPULAR_TVSHOWS_REJECTED = 'FETCH_POPULAR_TVSHOWS_REJECTED';

export const FETCH_MOVIE_CREDITS = 'FETCH_MOVIE_CREDITS';
export const FETCH_MOVIE_CREDITS_PENDING = 'FETCH_MOVIE_CREDITS_PENDING';
export const FETCH_MOVIE_CREDITS_FULFILLED = 'FETCH_MOVIE_CREDITS_FULFILLED';
export const FETCH_MOVIE_CREDITS_REJECTED = 'FETCH_MOVIE_CREDITS_REJECTED';

export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_PENDING = 'FETCH_MOVIE_DETAILS_PENDING';
export const FETCH_MOVIE_DETAILS_FULFILLED = 'FETCH_MOVIE_DETAILS_FULFILLED';
export const FETCH_MOVIE_DETAILS_REJECTED = 'FETCH_MOVIE_DETAILS_REJECTED';

export const FETCH_USERINFO_AND_CONFIGURATION = 'FETCH_USERINFO_AND_CONFIGURATION';
export const FETCH_POPULAR_MOVIES_AND_TVSHOWS = 'FETCH_POPULAR_MOVIES_AND_TVSHOWS';
export const FETCH_MOVIES_CREDITS_AND_DETAILS = 'FETCH_MOVIES_CREDITS_AND_DETAILS';
