// FETCH_GUEST_SESSION_ID ACTION NAMES

export const FETCH_GUEST_SESSION_ID = 'FETCH_GUEST_SESSION_ID';
export const FETCH_GUEST_SESSION_ID_PENDING = 'FETCH_GUEST_SESSION_ID_PENDING';
export const FETCH_GUEST_SESSION_ID_FULFILLED = 'FETCH_GUEST_SESSION_ID_FULFILLED';
export const FETCH_GUEST_SESSION_ID_REJECTED = 'FETCH_GUEST_SESSION_ID_REJECTED';

// FETCH_SESSION_ID ACTION NAMES

export const FETCH_SESSION_ID = 'FETCH_SESSION_ID';
export const FETCH_SESSION_ID_PENDING = 'FETCH_SESSION_ID_PENDING';
export const FETCH_SESSION_ID_FULFILLED = 'FETCH_SESSION_ID_FULFILLED';
export const FETCH_SESSION_ID_REJECTED = 'FETCH_SESSION_ID_REJECTED';

// FETCH_REQUEST_TOKEN ACTION NAMES

export const FETCH_REQUEST_TOKEN = 'FETCH_REQUEST_TOKEN';
export const FETCH_REQUEST_TOKEN_PENDING = 'FETCH_REQUEST_TOKEN_PENDING';
export const FETCH_REQUEST_TOKEN_FULFILLED = 'FETCH_REQUEST_TOKEN_FULFILLED';
export const FETCH_REQUEST_TOKEN_REJECTED = 'FETCH_REQUEST_TOKEN_REJECTED';

// FETCH_USER_INFO ACTION NAMES

export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_INFO_PENDING = 'FETCH_USER_INFO_PENDING';
export const FETCH_USER_INFO_FULFILLED = 'FETCH_USER_INFO_FULFILLED';
export const FETCH_USER_INFO_REJECTED = 'FETCH_USER_INFO_REJECTED';